window.RUTA9_PRODUCTS = [
  {code:'B1',name:'Burger clásica',category:'Burgers',price:8200,description:'Burger con queso gouda o cheddar.',favorite:true},
  {code:'B2',name:'Burger completa',category:'Burgers',price:9600,description:'Queso gouda, lechuga, tomate, cebolla morada y huevo frito.'},
  {code:'B3',name:'Burger BBQ',category:'Burgers',price:10900,description:'Queso cheddar, tocino, huevo frito, pepinillos y salsa BBQ.',favorite:true},
  {code:'B4',name:'Burger camarón limón',category:'Burgers',price:10400,description:'Camarones al limón y palta trozada.'},
  {code:'B5',name:'Burger Ruta 9',category:'Burgers',price:10400,description:'Queso gouda, tomate, palta trozada, mix de ajíes y nachos.'},
  {code:'B6',name:'Burger cheddar & onion',category:'Burgers',price:10300,description:'Queso cheddar, tocino, aros de cebolla apanados y salsa BBQ.'},
  {code:'B7',name:'La 420',category:'Burgers',price:8900,description:'Burger veggie de garbanzos, lechuga, cebollín grillado, palta y pepinillos.'},
  {code:'B8',name:'Burger queso crema',category:'Burgers',price:10100,description:'Queso crema y tocino crocante.'},
  {code:'B9',name:'Doble cuarto',category:'Burgers',price:13600,description:'Dos burgers y medallón de queso crocante.',favorite:true},
  {code:'B10',name:'Burger provoleta',category:'Burgers',price:12100,description:'Provoleta grillada, morrón y huevo frito.'},
  {code:'B11',name:'La vegetariana',category:'Burgers',price:9200,description:'Provoleta grillada, morrón, champiñones, cebolla caramelizada y tomate.'},
  {code:'B12',name:'Burger queso azul',category:'Burgers',price:9200,description:'Queso azul, cebolla caramelizada y salsa BBQ con ruibarbo.'},
  {code:'B13',name:'Burger cheddar plancha',category:'Burgers',price:9600,description:'Queso cheddar, cebolla a la plancha y huevo frito.'},
  {code:'B14',name:'Burger gouda',category:'Burgers',price:10600,description:'Queso gouda, cebolla caramelizada, tocino y huevo frito.'},
  {code:'B15',name:'La Tocineta',category:'Burgers',price:10600,description:'Tocino crocante, chutney de tocino y salsa tocinosa.'},
  {code:'B16',name:'La Kill Bill',category:'Burgers',price:12800,description:'Queso crema, camarones envueltos en tocino y salsa Ginzoo.',favorite:true},
  {code:'B17',name:'La Gran S',category:'Burgers',price:11700,description:'Queso cheddar, tocino, palta trozada y huevo frito.'},
  {code:'B18',name:'La Francesa',category:'Burgers',price:11600,description:'Queso gouda, queso azul, cebolla caramelizada y champiñones.'},
  {code:'B19',name:'La 36',category:'Burgers',price:11500,description:'Queso cheddar, tocino, aros de cebolla, pepinillos, BBQ y huevo.'},
  {code:'B20',name:'Los tres chanchitos',category:'Burgers',price:12200,description:'Queso gouda, tocino, pulled pork y longaniza.',favorite:true},
  {code:'B21',name:'La Limeña',category:'Burgers',price:9800,description:'Queso crema, ceviche de camarón, mix de ajíes y tortilla de maíz.'},
  {code:'B22',name:'Burger Club',category:'Burgers',price:9500,description:'Queso cheddar, lechuga, tomate, pepinillos y salsa club.'},
  {code:'B23',name:'Burger revuelta',category:'Burgers',price:10600,description:'Queso gouda, huevo revuelto, cebolla caramelizada y tocino.'},
  {code:'B24',name:'Veggie Thai',category:'Burgers',price:9800,description:'Burger de garbanzos, lechuga, champiñones, cebolla morada, ajíes, cebollín, Ginzoo y limón.'},
  {code:'B25',name:'Burger BLT',category:'Burgers',price:9600,description:'Burger, tocino, lechuga y tomate.'},
  {code:'K1',name:'Aros de cebolla',category:'Snacks',price:5500,description:'Aros de cebolla apanados, 15 unidades.'},
  {code:'K2',name:'Bastones de mozzarella',category:'Snacks',price:6800,description:'Bastones de mozzarella apanados, 10 unidades.',favorite:true},
  {code:'K3',name:'Mozzarella BBQ',category:'Snacks',price:7100,description:'Bastones de mozzarella apanados con salsa BBQ, 10 unidades.'},
  {code:'K4',name:'Condor Wings 5',category:'Snacks',price:6800,description:'Alitas con mostaza miel, BBQ, club o sriracha.'},
  {code:'K5',name:'Condor Wings 10',category:'Snacks',price:9200,description:'Alitas con mostaza miel, BBQ, club o sriracha.'},
  {code:'K6',name:'Condor Wings full',category:'Snacks',price:12500,description:'15 alitas, papas fritas, huevo frito y lactonesa.',favorite:true},
  {code:'K7',name:'Papas rústicas',category:'Papas',price:5200,description:'Porción de papas fritas rústicas.'},
  {code:'K8',name:'Papas & aros',category:'Papas',price:5500,description:'Papas rústicas con aros de cebolla apanados.'},
  {code:'K9',name:'Mix Ruta 9',category:'Papas',price:7200,description:'Mozzarella, aros de cebolla y papas rústicas.'},
  {code:'K10',name:'Papas provenzal',category:'Papas',price:5800,description:'Papas rústicas con ajo y perejil.'},
  {code:'K11',name:'Papas con huevos',category:'Papas',price:5800,description:'Papas fritas con dos huevos fritos o revueltos.'},
  {code:'K12',name:'Papas cheddar',category:'Papas',price:6500,description:'Salsa cheddar, tocino chips y pepinillos agridulces.',favorite:true},
  {code:'K13',name:'Papas queso crema',category:'Papas',price:6500,description:'Queso crema y tocino chips.'},
  {code:'K14',name:'Papas sriracha',category:'Papas',price:6200,description:'Mix de ajíes y salsa sriracha.'},
  {code:'K15',name:'Papas longaniza',category:'Papas',price:7200,description:'Longaniza ahumada de cerdo y dos huevos.'},
  {code:'K16',name:'Papas camarón limón',category:'Papas',price:8400,description:'Camarones al limón y palta trozada.'},
  {code:'K17',name:'Papas camarón parmesano',category:'Papas',price:9200,description:'Camarones a la parmesana.'},
  {code:'K18',name:'Papas a la vasca',category:'Papas',price:9100,description:'Papas fritas con camarones a la vasca.'},
  {code:'K19',name:'Papas brisket',category:'Papas',price:8500,description:'Brisket de ternera ahumada, cebolla caramelizada y huevo frito.',favorite:true},
  {code:'K20',name:'Papas prieta',category:'Papas',price:7100,description:'Prieta al verdeo y huevo frito.'},
  {code:'K21',name:'Hattori Hanzo',category:'Papas',price:8900,description:'Camarones envueltos en tocino, queso crema y salsa Ginzoo.'},
  {code:'BF',name:'Arma tu Burger',category:'Burger Factory',price:6800,description:'Elige base de carne, veggie o provoleta; luego agrega tus extras y salsa.',favorite:true},
  {code:'E1',name:'Cheddar',category:'Extras',price:1100,description:'Extra de queso cheddar.'},
  {code:'E2',name:'Salsa cheddar',category:'Extras',price:1500,description:'Porción extra de salsa cheddar.'},
  {code:'E3',name:'Gouda',category:'Extras',price:1100,description:'Extra de queso gouda.'},
  {code:'E4',name:'Queso crema',category:'Extras',price:1500,description:'Extra de queso crema.'},
  {code:'E5',name:'Provoleta',category:'Extras',price:2200,description:'Extra de provoleta.'},
  {code:'E6',name:'Palta trozada',category:'Extras',price:2400,description:'Porción extra de palta.'},
  {code:'E7',name:'Tocino',category:'Extras',price:1800,description:'Porción extra de tocino.'},
  {code:'E8',name:'Pulled pork',category:'Extras',price:2100,description:'Porción extra de pulled pork.'},
  {code:'E9',name:'Burger extra',category:'Extras',price:2200,description:'Medallón de burger adicional.'},
  {code:'E10',name:'Salsa extra',category:'Extras',price:600,description:'Lactonesa o BBQ.'}
];
